# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gigyEsL8FE7_jaqdRonUiTf7pDfPvUej
"""

pip install chatterbot

pip install chatterbot_corpus

# Importing chatterbot
from chatterbot import ChatBot

# Create object of ChatBot class
bot = ChatBot('Buddy')

# Create object of ChatBot class with Storage Adapter
bot = ChatBot(
    'Buddy',
    storage_adapter='chatterbot.storage.SQLStorageAdapter',
    database_uri='sqlite:///database.sqlite3'
)

# Create object of ChatBot class with Logic Adapter
bot = ChatBot(
    'Buddy',  
    logic_adapters=[
        'chatterbot.logic.BestMatch',
        'chatterbot.logic.TimeLogicAdapter'],
)

# Inport ListTrainer
from chatterbot.trainers import ListTrainer

trainer = ListTrainer(bot)

trainer.train([
'Hi',
'Hello',
'I want to know about the menstrual cycle',
'Please, tell me what are the problems that you are facing',
'My cycle is dealy.',
'Well thats normal, often women cycles are delayed',
'How long it will take the cycle to reoccur?',
'It can take about 2-3 weeks',
'Can I connect with doctor?',
'Sure',
'Thanks',
'Any other problem?',
'No Problem! Have a Good Day!',

])

# Get a response to the input text 'I would like to book a flight.'
response = bot.get_response('I have a complaint.')

print("Bot Response:", response)

name=input("Enter Your Name: ")
print("Welcome to the Bot Service! Let me know how can I help you?")
while True:
    request=input(name+':')
    if request=='Bye' or request =='bye':
        print('Bot: Bye')
        break
    else:
        response=bot.get_response(request)
        print('Bot:',response)